name: Expo Publish CI

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run validate

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install expo-cli@3
      - run: npx expo login --non-interactive -u ${{ secrets.EXPO_CLI_USERNAME }}
        env:
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: npx expo publish --non-interactive
